name: Link Check

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: -vv --no-progress "**/*.md" "README.md"  --exclude-path "agentic_ai/agents/agent_framework/multi_agent/MAGENTIC_README.md"
